import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

const LANGUAGE_KEY = '@marrakech_bites_language';

export const LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'fr', label: 'Français' },
  { code: 'ar', label: 'العربية' },
];

const translations = {
  en: {},
  fr: {
    'Language': 'Langue',
    'Choose language': 'Choisir la langue',
    'English': 'Anglais',
    'Français': 'Français',
    'العربية': 'Arabe',
    'Menu': 'Menu',
    'Orders': 'Commandes',
    'Profile': 'Profil',
    'Your profile': 'Votre profil',
    'Personal details': 'Informations personnelles',
    'Email notifications': 'Notifications par e-mail',
    'Order status changes': 'Mises à jour des commandes',
    'Password changes': 'Changements de mot de passe',
    'Special offers': 'Offres spéciales',
    'Newsletter': 'Infolettre',
    'Settings': 'Paramètres',
    'Change password': 'Changer le mot de passe',
    'Sync database': 'Synchroniser le menu',
    'Working…': 'En cours…',
    'Log out': 'Se déconnecter',
    'Are you sure you want to log out?': 'Voulez-vous vraiment vous déconnecter ?',
    'Cancel': 'Annuler',
    'First name': 'Prénom',
    'Last name': 'Nom',
    'Last name (optional)': 'Nom (facultatif)',
    'Email': 'E-mail',
    'Phone': 'Téléphone',
    'Save changes': 'Enregistrer',
    'Discard': 'Ignorer',
    'Change profile picture': 'Changer la photo de profil',
    'Allow photo access to choose a picture.': 'Autorisez l’accès aux photos pour en choisir une.',
    'Failed to pick image.': 'Impossible de choisir la photo.',
    'Profile picture': 'Photo de profil',
    'Choose new photo': 'Choisir une nouvelle photo',
    'Remove photo': 'Supprimer la photo',
    'Profile updated.': 'Profil mis à jour.',
    'Unable to save your profile.': 'Impossible d’enregistrer le profil.',
    'Failed to log out. Please try again.': 'Déconnexion impossible. Réessayez.',
    'Menu synced · {count} items.': 'Menu synchronisé · {count} articles.',
    'Sync failed.': 'Échec de la synchronisation.',
    'Failed to sync the menu.': 'Impossible de synchroniser le menu.',
    'Welcome back': 'Ravi de vous revoir',
    'Log in to order your favourites.': 'Connectez-vous pour commander vos plats préférés.',
    'Password': 'Mot de passe',
    'Log in': 'Se connecter',
    'Create account': 'Créer un compte',
    'Continue as guest': 'Continuer en invité',
    'Sign up': 'S’inscrire',
    'It takes less than a minute.': 'Cela prend moins d’une minute.',
    'Confirm password': 'Confirmer le mot de passe',
    'I already have an account': 'J’ai déjà un compte',
    'Enter a valid email address.': 'Saisissez une adresse e-mail valide.',
    'At least 6 characters.': 'Au moins 6 caractères.',
    'At least 8 characters.': 'Au moins 8 caractères.',
    'Letters and spaces only.': 'Lettres et espaces uniquement.',
    'Passwords do not match.': 'Les mots de passe ne correspondent pas.',
    'Please fix the highlighted fields.': 'Veuillez corriger les champs indiqués.',
    'Failed to log in. Please try again.': 'Connexion impossible. Réessayez.',
    'Failed to register. Please try again.': 'Inscription impossible. Réessayez.',
    'Current password': 'Mot de passe actuel',
    'New password': 'Nouveau mot de passe',
    'Confirm new password': 'Confirmer le nouveau mot de passe',
    'Update password': 'Mettre à jour le mot de passe',
    'Password changed.': 'Mot de passe modifié.',
    'Your orders': 'Vos commandes',
    'No orders yet': 'Aucune commande',
    'Your orders and their progress will show up here.': 'Vos commandes et leur suivi apparaîtront ici.',
    'item': 'article',
    'items': 'articles',
    'New update': 'Nouvelle mise à jour',
    'Placed': 'Reçue',
    'Preparing': 'En préparation',
    'On the way': 'En livraison',
    'Delivered': 'Livrée',
    'Order cancelled': 'Commande annulée',
    'Order': 'Commande',
    'Order details': 'Détails de la commande',
    'This order could not be found.': 'Commande introuvable.',
    'Cancel order': 'Annuler la commande',
    'Are you sure you want to cancel this order?': 'Voulez-vous vraiment annuler cette commande ?',
    'Keep order': 'Garder la commande',
    'Order cancelled.': 'Commande annulée.',
    'Could not cancel the order.': 'Impossible d’annuler la commande.',
    'Items added to your cart.': 'Articles ajoutés au panier.',
    'View cart': 'Voir le panier',
    'Select a rating first.': 'Veuillez d’abord choisir une note.',
    'Thanks for your feedback!': 'Merci pour votre avis !',
    'Status': 'Statut',
    'Items': 'Articles',
    'Delivery': 'Livraison',
    'Summary': 'Récapitulatif',
    'Subtotal': 'Sous-total',
    'Tax': 'Taxes',
    'Your review': 'Votre avis',
    'Rate your order': 'Évaluer la commande',
    'Share your experience (optional)': 'Partagez votre expérience (facultatif)',
    'Submit review': 'Envoyer l’avis',
    'Reorder': 'Recommander',
    'Cancel order': 'Annuler la commande',
    'No dishes found': 'Aucun plat trouvé',
    'Try a different search or category.': 'Essayez une autre recherche ou catégorie.',
    'All': 'Tout',
    'Starters': 'Entrées',
    'Mains': 'Plats',
    'Desserts': 'Desserts',
    'Drinks': 'Boissons',
    'Out of stock': 'Indisponible',
    'Add {name} to cart': 'Ajouter {name} au panier',
    'Sign in to add items to your cart.': 'Connectez-vous pour ajouter des articles au panier.',
    'Sign in': 'Se connecter',
    'Could not add the item. Please try again.': 'Impossible d’ajouter cet article. Réessayez.',
    'Image unavailable': 'Image indisponible',
    'No image available': 'Aucune image disponible',
    'Menu item': 'Article du menu',
    'Menu Item': 'Article du menu',
    'Currently Out of Stock': 'Actuellement indisponible',
    'Price': 'Prix',
    'Prepare Time: ': 'Préparation : ',
    'Extra Cheese': 'Fromage supplémentaire',
    'Spicy Sauce': 'Sauce piquante',
    'Gluten Free': 'Sans gluten',
    'Quantity': 'Quantité',
    'TOTAL': 'TOTAL',
    'Adding to Cart...': 'Ajout au panier…',
    'Add to Cart for {price}': 'Ajouter au panier pour {price}',
    'Failed to add item to cart.': 'Impossible d’ajouter au panier.',
    'An unexpected error occurred.': 'Une erreur inattendue est survenue.',
    'Sign in to add items to your cart.': 'Connectez-vous pour ajouter des articles au panier.',
    'Cart': 'Panier',
    'Your Cart is Empty': 'Votre panier est vide',
    'Add items to your order to continue': 'Ajoutez des articles pour continuer',
    'Continue Shopping': 'Continuer les achats',
    'Checkout': 'Paiement',
    'Order Items ({count})': 'Articles ({count})',
    'Order Summary': 'Récapitulatif de commande',
    'Tax (10%)': 'Taxes (10 %)',
    'Total': 'Total',
    'Delivery Information': 'Informations de livraison',
    'Delivery Address': 'Adresse de livraison',
    'Phone Number': 'Numéro de téléphone',
    'Special Instructions (Optional)': 'Instructions spéciales (facultatif)',
    'Processing...': 'Traitement…',
    'Place Order': 'Commander',
    'Processing your order...': 'Traitement de votre commande…',
    'Register to place an order.': 'Inscrivez-vous pour commander.',
    'Register': 'S’inscrire',
    'Please enter a delivery address.': 'Veuillez saisir une adresse de livraison.',
    'Please enter a phone number.': 'Veuillez saisir un numéro de téléphone.',
    'Your cart is empty.': 'Votre panier est vide.',
    'Order placed · {price}': 'Commande passée · {price}',
    'Failed to place order. Please try again.': 'Commande impossible. Réessayez.',
    'Login': 'Connexion',
    'Sign Up': 'S’inscrire',
    'Continue as Guest': 'Continuer en invité',
    'Discover bold Moroccan-inspired street food, made for sharing and enjoying anywhere.': 'Découvrez une cuisine de rue inspirée du Maroc, à partager et à savourer partout.',
    '© 2026 Marrakech Bites. All rights reserved.': '© 2026 Marrakech Bites. Tous droits réservés.',
    'Could not load the menu. Pull down to retry.': 'Impossible de charger le menu. Faites glisser vers le bas pour réessayer.',
    'Search failed. Please try again.': 'Échec de la recherche. Réessayez.',
    'Could not refresh the menu.': 'Impossible d’actualiser le menu.',
    'Moroccan-inspired street food.': 'Cuisine de rue inspirée du Maroc.',
    'Enter a valid Moroccan number (+212 and 9 digits).': 'Saisissez un numéro marocain valide (+212 et 9 chiffres).',
    'you@example.com': 'vous@exemple.com',
    'Your password': 'Votre mot de passe',
    'Order status: {status}': 'État de la commande : {status}',
    'Search the menu': 'Rechercher dans le menu',
    'Clear search': 'Effacer la recherche',
    'View cart, {count} items': 'Voir le panier, {count} articles',
    'Sign in Required': 'Connexion requise',
    'Please sign in or create an account to add items to your cart': 'Connectez-vous ou créez un compte pour ajouter des articles au panier.',
    'Sign In': 'Se connecter',
    'Dismiss': 'Fermer',
    'Added to cart': 'Ajouté au panier',
    'Qty {quantity} · {price}': 'Qté {quantity} · {price}',
    'Keep browsing': 'Continuer à parcourir',
    'Order from {date}, {price}': 'Commande du {date}, {price}',
    'Placed {date} at {time}': 'Passée le {date} à {time}',
    'Qty {quantity}': 'Qté {quantity}',
    '{count} stars': '{count} étoiles',
    'Extras': 'Suppléments',
    'Go back': 'Retour',
    'V1.0 Copyright © 2025': 'V1.0 Droits d’auteur © 2025',
    'Fast, fresh bites with Moroccan-inspired flavor.': 'Des bouchées rapides et fraîches aux saveurs marocaines.',
    'Loading menu item': 'Chargement du plat',
    'Next': 'Suivant',
  },
  ar: {
    'Language': 'اللغة',
    'Choose language': 'اختر اللغة',
    'English': 'الإنجليزية',
    'Français': 'الفرنسية',
    'العربية': 'العربية',
    'Menu': 'القائمة',
    'Orders': 'الطلبات',
    'Profile': 'الملف الشخصي',
    'Your profile': 'ملفك الشخصي',
    'Personal details': 'المعلومات الشخصية',
    'Email notifications': 'إشعارات البريد الإلكتروني',
    'Order status changes': 'تحديثات حالة الطلب',
    'Password changes': 'تغييرات كلمة المرور',
    'Special offers': 'عروض خاصة',
    'Newsletter': 'النشرة البريدية',
    'Settings': 'الإعدادات',
    'Change password': 'تغيير كلمة المرور',
    'Sync database': 'مزامنة القائمة',
    'Working…': 'جارٍ العمل…',
    'Log out': 'تسجيل الخروج',
    'Are you sure you want to log out?': 'هل تريد تسجيل الخروج؟',
    'Cancel': 'إلغاء',
    'First name': 'الاسم الأول',
    'Last name': 'اسم العائلة',
    'Last name (optional)': 'اسم العائلة (اختياري)',
    'Email': 'البريد الإلكتروني',
    'Phone': 'الهاتف',
    'Save changes': 'حفظ التغييرات',
    'Discard': 'تجاهل',
    'Change profile picture': 'تغيير صورة الملف الشخصي',
    'Allow photo access to choose a picture.': 'يرجى السماح بالوصول إلى الصور لاختيار صورة.',
    'Failed to pick image.': 'تعذر اختيار الصورة.',
    'Profile picture': 'صورة الملف الشخصي',
    'Choose new photo': 'اختيار صورة جديدة',
    'Remove photo': 'إزالة الصورة',
    'Profile updated.': 'تم تحديث الملف الشخصي.',
    'Unable to save your profile.': 'تعذر حفظ الملف الشخصي.',
    'Failed to log out. Please try again.': 'تعذر تسجيل الخروج. حاول مرة أخرى.',
    'Menu synced · {count} items.': 'تمت مزامنة القائمة · {count} عناصر.',
    'Sync failed.': 'فشلت المزامنة.',
    'Failed to sync the menu.': 'تعذرت مزامنة القائمة.',
    'Welcome back': 'مرحبًا بعودتك',
    'Log in to order your favourites.': 'سجّل الدخول لطلب أطباقك المفضلة.',
    'Password': 'كلمة المرور',
    'Log in': 'تسجيل الدخول',
    'Create account': 'إنشاء حساب',
    'Continue as guest': 'المتابعة كضيف',
    'Sign up': 'إنشاء حساب',
    'It takes less than a minute.': 'لن يستغرق الأمر أكثر من دقيقة.',
    'Confirm password': 'تأكيد كلمة المرور',
    'I already have an account': 'لدي حساب بالفعل',
    'Enter a valid email address.': 'أدخل بريدًا إلكترونيًا صالحًا.',
    'At least 6 characters.': '6 أحرف على الأقل.',
    'At least 8 characters.': '8 أحرف على الأقل.',
    'Letters and spaces only.': 'استخدم الحروف والمسافات فقط.',
    'Passwords do not match.': 'كلمتا المرور غير متطابقتين.',
    'Please fix the highlighted fields.': 'يرجى تصحيح الحقول المحددة.',
    'Failed to log in. Please try again.': 'تعذر تسجيل الدخول. حاول مرة أخرى.',
    'Failed to register. Please try again.': 'تعذر إنشاء الحساب. حاول مرة أخرى.',
    'Current password': 'كلمة المرور الحالية',
    'New password': 'كلمة المرور الجديدة',
    'Confirm new password': 'تأكيد كلمة المرور الجديدة',
    'Update password': 'تحديث كلمة المرور',
    'Password changed.': 'تم تغيير كلمة المرور.',
    'Your orders': 'طلباتك',
    'No orders yet': 'لا توجد طلبات بعد',
    'Your orders and their progress will show up here.': 'ستظهر طلباتك وحالتها هنا.',
    'item': 'عنصر',
    'items': 'عناصر',
    'New update': 'تحديث جديد',
    'Placed': 'تم الاستلام',
    'Preparing': 'قيد التحضير',
    'On the way': 'في الطريق',
    'Delivered': 'تم التوصيل',
    'Order cancelled': 'تم إلغاء الطلب',
    'Order': 'الطلب',
    'Order details': 'تفاصيل الطلب',
    'This order could not be found.': 'تعذر العثور على هذا الطلب.',
    'Cancel order': 'إلغاء الطلب',
    'Are you sure you want to cancel this order?': 'هل أنت متأكد من إلغاء هذا الطلب؟',
    'Keep order': 'الاحتفاظ بالطلب',
    'Order cancelled.': 'تم إلغاء الطلب.',
    'Could not cancel the order.': 'تعذر إلغاء الطلب.',
    'Items added to your cart.': 'تمت إضافة العناصر إلى سلتك.',
    'View cart': 'عرض السلة',
    'Select a rating first.': 'اختر تقييمًا أولاً.',
    'Thanks for your feedback!': 'شكرًا على ملاحظاتك!',
    'Status': 'الحالة',
    'Items': 'العناصر',
    'Delivery': 'التوصيل',
    'Summary': 'الملخص',
    'Subtotal': 'المجموع الفرعي',
    'Tax': 'الضريبة',
    'Your review': 'تقييمك',
    'Rate your order': 'قيّم طلبك',
    'Share your experience (optional)': 'شارك تجربتك (اختياري)',
    'Submit review': 'إرسال التقييم',
    'Reorder': 'إعادة الطلب',
    'No dishes found': 'لم يتم العثور على أطباق',
    'Try a different search or category.': 'جرّب بحثًا أو فئة مختلفة.',
    'All': 'الكل',
    'Starters': 'المقبلات',
    'Mains': 'الأطباق الرئيسية',
    'Desserts': 'الحلويات',
    'Drinks': 'المشروبات',
    'Out of stock': 'غير متوفر',
    'Add {name} to cart': 'إضافة {name} إلى السلة',
    'Sign in to add items to your cart.': 'سجّل الدخول لإضافة عناصر إلى السلة.',
    'Sign in': 'تسجيل الدخول',
    'Could not add the item. Please try again.': 'تعذرت إضافة العنصر. حاول مرة أخرى.',
    'Image unavailable': 'الصورة غير متاحة',
    'No image available': 'لا توجد صورة متاحة',
    'Menu item': 'عنصر من القائمة',
    'Menu Item': 'عنصر من القائمة',
    'Currently Out of Stock': 'غير متوفر حاليًا',
    'Price': 'السعر',
    'Prepare Time: ': 'وقت التحضير: ',
    'Extra Cheese': 'جبن إضافي',
    'Spicy Sauce': 'صلصة حارة',
    'Gluten Free': 'خالٍ من الغلوتين',
    'Quantity': 'الكمية',
    'TOTAL': 'الإجمالي',
    'Adding to Cart...': 'جارٍ الإضافة إلى السلة…',
    'Add to Cart for {price}': 'أضف إلى السلة مقابل {price}',
    'Failed to add item to cart.': 'تعذرت إضافة العنصر إلى السلة.',
    'An unexpected error occurred.': 'حدث خطأ غير متوقع.',
    'Cart': 'السلة',
    'Your Cart is Empty': 'سلتك فارغة',
    'Add items to your order to continue': 'أضف عناصر إلى طلبك للمتابعة',
    'Continue Shopping': 'متابعة التسوق',
    'Checkout': 'إتمام الطلب',
    'Order Items ({count})': 'عناصر الطلب ({count})',
    'Order Summary': 'ملخص الطلب',
    'Tax (10%)': 'الضريبة (10٪)',
    'Total': 'الإجمالي',
    'Delivery Information': 'معلومات التوصيل',
    'Delivery Address': 'عنوان التوصيل',
    'Phone Number': 'رقم الهاتف',
    'Special Instructions (Optional)': 'تعليمات خاصة (اختياري)',
    'Processing...': 'جارٍ المعالجة…',
    'Place Order': 'تأكيد الطلب',
    'Processing your order...': 'جارٍ معالجة طلبك…',
    'Register to place an order.': 'أنشئ حسابًا لإرسال الطلب.',
    'Register': 'إنشاء حساب',
    'Please enter a delivery address.': 'أدخل عنوان التوصيل.',
    'Please enter a phone number.': 'أدخل رقم الهاتف.',
    'Your cart is empty.': 'سلتك فارغة.',
    'Order placed · {price}': 'تم إرسال الطلب · {price}',
    'Failed to place order. Please try again.': 'تعذر إرسال الطلب. حاول مرة أخرى.',
    'Login': 'تسجيل الدخول',
    'Sign Up': 'إنشاء حساب',
    'Continue as Guest': 'المتابعة كضيف',
    'Discover bold Moroccan-inspired street food, made for sharing and enjoying anywhere.': 'اكتشف مأكولات شارع مغربية جريئة، مثالية للمشاركة والاستمتاع في أي مكان.',
    '© 2026 Marrakech Bites. All rights reserved.': '© 2026 مراكش بايتس. جميع الحقوق محفوظة.',
    'Could not load the menu. Pull down to retry.': 'تعذر تحميل القائمة. اسحب لأسفل للمحاولة مجددًا.',
    'Search failed. Please try again.': 'فشل البحث. حاول مرة أخرى.',
    'Could not refresh the menu.': 'تعذر تحديث القائمة.',
    'Moroccan-inspired street food.': 'مأكولات شارع مستوحاة من المغرب.',
    'Enter a valid Moroccan number (+212 and 9 digits).': 'أدخل رقمًا مغربيًا صالحًا (+212 وتسعة أرقام).',
    'you@example.com': 'you@example.com',
    'Your password': 'كلمة المرور',
    'Order status: {status}': 'حالة الطلب: {status}',
    'Search the menu': 'ابحث في القائمة',
    'Clear search': 'مسح البحث',
    'View cart, {count} items': 'عرض السلة، {count} عناصر',
    'Sign in Required': 'تسجيل الدخول مطلوب',
    'Please sign in or create an account to add items to your cart': 'سجّل الدخول أو أنشئ حسابًا لإضافة عناصر إلى سلتك.',
    'Sign In': 'تسجيل الدخول',
    'Dismiss': 'إغلاق',
    'Added to cart': 'تمت الإضافة إلى السلة',
    'Qty {quantity} · {price}': 'الكمية {quantity} · {price}',
    'Keep browsing': 'متابعة التصفح',
    'Order from {date}, {price}': 'طلب بتاريخ {date}، {price}',
    'Placed {date} at {time}': 'تم الطلب في {date} الساعة {time}',
    'Qty {quantity}': 'الكمية {quantity}',
    '{count} stars': '{count} نجوم',
    'Extras': 'إضافات',
    'Go back': 'رجوع',
    'V1.0 Copyright © 2025': 'الإصدار 1.0 حقوق النشر © 2025',
    'Fast, fresh bites with Moroccan-inspired flavor.': 'وجبات سريعة وطازجة بنكهات مستوحاة من المغرب.',
    'Loading menu item': 'جارٍ تحميل عنصر القائمة',
    'Next': 'التالي',
  },
};

const LanguageContext = createContext({
  language: 'en',
  isRTL: false,
  setLanguage: async () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState('en');

  useEffect(() => {
    AsyncStorage.getItem(LANGUAGE_KEY)
      .then((stored) => {
        if (LANGUAGES.some(({ code }) => code === stored)) setLanguageState(stored);
      })
      .catch(() => {});
  }, []);

  const setLanguage = async (nextLanguage) => {
    if (!LANGUAGES.some(({ code }) => code === nextLanguage)) return;
    setLanguageState(nextLanguage);
    try {
      await AsyncStorage.setItem(LANGUAGE_KEY, nextLanguage);
    } catch {
      // Keep the selected language for the current session if storage is unavailable.
    }
  };

  const value = useMemo(() => ({
    language,
    isRTL: language === 'ar',
    setLanguage,
    t: (key, params = {}) => {
      const template = translations[language][key] || translations.en[key] || key;
      return template.replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? `{${name}}`));
    },
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}